
[package]
name = "audio_ingest"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
klarnet-core = { path = "../core" }
tokio.workspace = true
tracing.workspace = true
