# config/klarnet.toml

[app]
language = "ru"
mode = "gpu"
pre_roll_ms = 1000
max_utterance_s = 120
log_level = "info"

[audio]
sample_rate = 16000
channels = 1
bits_per_sample = 16
buffer_size = 1024
device = "default"

[vad]
mode = "webrtc"  # webrtc | energy | hybrid
aggressiveness = 2  # 0-3
frame_duration_ms = 30
min_speech_duration_ms = 200
min_silence_duration_ms = 500
energy_threshold = 0.01
speech_pad_ms = 300

[stt]
model_path = "models/faster-whisper-medium"
model_size = "medium"  # tiny | base | small | medium | large
compute_type = "int8_float16"
language = "ru"
beam_size = 5
vad_filter = true
word_timestamps = true
device = "cuda"
device_index = 0
num_workers = 1
batch_size = 1
max_segment_length = 30.0

[nlu]
mode = "hybrid"  # local | llm | hybrid
wake_words = ["Кларнет", "ассистент", "компьютер"]
confidence_threshold = 0.7

[nlu.local]
patterns_file = "config/patterns.yaml"
entities_file = "config/entities.yaml"

[nlu.llm]
provider = "openrouter"
model = "deepseek/deepseek-chat"
api_key_env = "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"
max_tokens = 500
temperature = 0.3
timeout_s = 5

[actions]
enabled_modules = ["system", "smart_home", "web"]
scripts_dir = "scripts/actions"

[actions.smart_home]
api_url = "http://homeassistant.local:8123"
api_token_env = "HASS_TOKEN"

[tts]
enabled = true
engine = "silero"  # silero | vits | piper
model = "v4_ru"
speaker = "xenia"
sample_rate = 48000
speed = 1.0
device = "cpu"

[api]
enabled = true
host = "0.0.0.0"
port = 3000
cors_origins = ["*"]

[api.auth]
enabled = false
jwt_secret_env = "JWT_SECRET"

[metrics]
enabled = true
prometheus_port = 9090
export_interval_s = 10

[observability]
traces_enabled = true
traces_endpoint = "http://localhost:4317"
service_name = "klarnet"